//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApp {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ConsoleApp.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1786
        ///571
        ///1689
        ///1853
        ///1817
        ///1549
        ///1079
        ///1755
        ///1973
        ///1453
        ///1139
        ///1576
        ///1928
        ///1634
        ///1961
        ///1995
        ///1272
        ///1839
        ///1976
        ///1664
        ///1956
        ///1933
        ///1981
        ///1665
        ///1057
        ///1798
        ///1485
        ///2004
        ///1990
        ///2002
        ///82
        ///1922
        ///1544
        ///201
        ///1730
        ///1607
        ///1597
        ///1098
        ///1490
        ///1955
        ///1194
        ///1733
        ///1245
        ///1761
        ///1709
        ///1143
        ///1828
        ///1450
        ///1569
        ///1997
        ///1943
        ///1555
        ///1958
        ///1176
        ///1858
        ///1937
        ///1560
        ///1979
        ///1962
        ///1658
        ///1959
        ///2007
        ///1636
        ///1460
        ///348
        ///1084
        ///1952
        ///1162
        ///1772
        ///701
        ///1462
        ///1680
        ///1639
        ///1625
        ///1060
        ///1600
        ///1631
        ///1638
        ///1350
        ///1675
        ///1366
        ///1244
        ///1413
        ///994
        ///1533
        ///1199
        ///165 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DayOne {
            get {
                return ResourceManager.GetString("DayOne", resourceCulture);
            }
        }
    }
}
